#!/bin/bash
# Upload images to R2
# Usage: bash scripts/upload-to-r2.sh

npx wrangler r2 object put --remote netereka/products/smartphones/google-pixel-10-pro-xl.webp --file=scripts/images/google-pixel-10-pro-xl.webp --content-type=image/webp
npx wrangler r2 object put --remote netereka/products/smartphones/google-pixel-10-pro-512go.webp --file=scripts/images/google-pixel-10-pro-512go.webp --content-type=image/webp
npx wrangler r2 object put --remote netereka/products/smartphones/apple-iphone-17-5g.webp --file=scripts/images/apple-iphone-17-5g.webp --content-type=image/webp
npx wrangler r2 object put --remote netereka/products/smartphones/galaxy-z-fold-7.webp --file=scripts/images/galaxy-z-fold-7.webp --content-type=image/webp
npx wrangler r2 object put --remote netereka/products/smartphones/iphone-16-pro-max.webp --file=scripts/images/iphone-16-pro-max.webp --content-type=image/webp
npx wrangler r2 object put --remote netereka/products/smartphones/iphone-16-pro.webp --file=scripts/images/iphone-16-pro.webp --content-type=image/webp
npx wrangler r2 object put --remote netereka/products/smartphones/iphone-16-plus.webp --file=scripts/images/iphone-16-plus.webp --content-type=image/webp
npx wrangler r2 object put --remote netereka/products/smartphones/iphone-16.webp --file=scripts/images/iphone-16.webp --content-type=image/webp
npx wrangler r2 object put --remote netereka/products/smartphones/samsung-s25-ultra.webp --file=scripts/images/samsung-s25-ultra.webp --content-type=image/webp
npx wrangler r2 object put --remote netereka/products/smartphones/samsung-s25.webp --file=scripts/images/samsung-s25.webp --content-type=image/webp
npx wrangler r2 object put --remote netereka/products/smartphones/samsung-s25.webp --file=scripts/images/samsung-s25.webp --content-type=image/webp
npx wrangler r2 object put --remote netereka/products/smartphones/samsung-s24-ultra.webp --file=scripts/images/samsung-s24-ultra.webp --content-type=image/webp
npx wrangler r2 object put --remote netereka/products/smartphones/samsung-s24.webp --file=scripts/images/samsung-s24.webp --content-type=image/webp
npx wrangler r2 object put --remote netereka/products/smartphones/honor-200.webp --file=scripts/images/honor-200.webp --content-type=image/webp
npx wrangler r2 object put --remote netereka/products/smartphones/honor-400-lite.webp --file=scripts/images/honor-400-lite.webp --content-type=image/webp
npx wrangler r2 object put --remote netereka/products/smartphones/honor-400-pro.webp --file=scripts/images/honor-400-pro.webp --content-type=image/webp
npx wrangler r2 object put --remote netereka/products/smartphones/honor-magic-6-pro.webp --file=scripts/images/honor-magic-6-pro.webp --content-type=image/webp
npx wrangler r2 object put --remote netereka/products/smartphones/honor-magic-7-pro.webp --file=scripts/images/honor-magic-7-pro.webp --content-type=image/webp
npx wrangler r2 object put --remote netereka/products/smartphones/honor-magic-v2.webp --file=scripts/images/honor-magic-v2.webp --content-type=image/webp
npx wrangler r2 object put --remote netereka/products/smartphones/honor-magic-v3.webp --file=scripts/images/honor-magic-v3.webp --content-type=image/webp
npx wrangler r2 object put --remote netereka/products/smartphones/honor-magic-v5-16go-ram-512go.webp --file=scripts/images/honor-magic-v5-16go-ram-512go.webp --content-type=image/webp
npx wrangler r2 object put --remote netereka/products/smartphones/honor-x7b.webp --file=scripts/images/honor-x7b.webp --content-type=image/webp
npx wrangler r2 object put --remote netereka/products/smartphones/honor-x7c.webp --file=scripts/images/honor-x7c.webp --content-type=image/webp
npx wrangler r2 object put --remote netereka/products/smartphones/honor-x9c.webp --file=scripts/images/honor-x9c.webp --content-type=image/webp
npx wrangler r2 object put --remote netereka/products/smartphones/huawei-mate-x3.webp --file=scripts/images/huawei-mate-x3.webp --content-type=image/webp
npx wrangler r2 object put --remote netereka/products/smartphones/huawei-mate-x6.webp --file=scripts/images/huawei-mate-x6.webp --content-type=image/webp
npx wrangler r2 object put --remote netereka/products/smartphones/huawei-mate-xt.webp --file=scripts/images/huawei-mate-xt.webp --content-type=image/webp
npx wrangler r2 object put --remote netereka/products/smartphones/huawei-nova-11-pro.webp --file=scripts/images/huawei-nova-11-pro.webp --content-type=image/webp
npx wrangler r2 object put --remote netereka/products/smartphones/huawei-nova-12i.webp --file=scripts/images/huawei-nova-12i.webp --content-type=image/webp
npx wrangler r2 object put --remote netereka/products/smartphones/huawei-nova-12s.webp --file=scripts/images/huawei-nova-12s.webp --content-type=image/webp
npx wrangler r2 object put --remote netereka/products/smartphones/huawei-pura-70.webp --file=scripts/images/huawei-pura-70.webp --content-type=image/webp
npx wrangler r2 object put --remote netereka/products/smartphones/huawei-pura-70-pro.webp --file=scripts/images/huawei-pura-70-pro.webp --content-type=image/webp
npx wrangler r2 object put --remote netereka/products/smartphones/huawei-pura-70-ultra.webp --file=scripts/images/huawei-pura-70-ultra.webp --content-type=image/webp
npx wrangler r2 object put --remote netereka/products/smartphones/pixel-7.webp --file=scripts/images/pixel-7.webp --content-type=image/webp
npx wrangler r2 object put --remote netereka/products/tablettes/ipad-10th-gen-2022.webp --file=scripts/images/ipad-10th-gen-2022.webp --content-type=image/webp
npx wrangler r2 object put --remote netereka/products/tablettes/ipad-11th-gen-2025.webp --file=scripts/images/ipad-11th-gen-2025.webp --content-type=image/webp
npx wrangler r2 object put --remote netereka/products/tablettes/ipad-mini-6-2022.webp --file=scripts/images/ipad-mini-6-2022.webp --content-type=image/webp
npx wrangler r2 object put --remote netereka/products/tablettes/ipad-mini-7-2024.webp --file=scripts/images/ipad-mini-7-2024.webp --content-type=image/webp
npx wrangler r2 object put --remote netereka/products/tablettes/ipad-air-6th-m2-2024.webp --file=scripts/images/ipad-air-6th-m2-2024.webp --content-type=image/webp
npx wrangler r2 object put --remote netereka/products/tablettes/ipad-air-7th-m3-2025.webp --file=scripts/images/ipad-air-7th-m3-2025.webp --content-type=image/webp
npx wrangler r2 object put --remote netereka/products/tablettes/ipad-pro-m4-2024.webp --file=scripts/images/ipad-pro-m4-2024.webp --content-type=image/webp
npx wrangler r2 object put --remote netereka/products/tablettes/samsung-tab-a9.webp --file=scripts/images/samsung-tab-a9.webp --content-type=image/webp
npx wrangler r2 object put --remote netereka/products/tablettes/samsung-tab-s9.webp --file=scripts/images/samsung-tab-s9.webp --content-type=image/webp
npx wrangler r2 object put --remote netereka/products/tablettes/samsung-tab-s9-fe.webp --file=scripts/images/samsung-tab-s9-fe.webp --content-type=image/webp
npx wrangler r2 object put --remote netereka/products/tablettes/samsung-tab-s9-fe.webp --file=scripts/images/samsung-tab-s9-fe.webp --content-type=image/webp
npx wrangler r2 object put --remote netereka/products/tablettes/samsung-tab-s9.webp --file=scripts/images/samsung-tab-s9.webp --content-type=image/webp
npx wrangler r2 object put --remote netereka/products/tablettes/samsung-tab-s9-ultra.webp --file=scripts/images/samsung-tab-s9-ultra.webp --content-type=image/webp
npx wrangler r2 object put --remote netereka/products/tablettes/samsung-tab-s10-ultra.webp --file=scripts/images/samsung-tab-s10-ultra.webp --content-type=image/webp
npx wrangler r2 object put --remote netereka/products/tablettes/redmi-pad-2-4g.webp --file=scripts/images/redmi-pad-2-4g.webp --content-type=image/webp
npx wrangler r2 object put --remote netereka/products/tablettes/redmi-pad-6s-pro.webp --file=scripts/images/redmi-pad-6s-pro.webp --content-type=image/webp
npx wrangler r2 object put --remote netereka/products/tablettes/redmi-pad-2.webp --file=scripts/images/redmi-pad-2.webp --content-type=image/webp
npx wrangler r2 object put --remote netereka/products/tablettes/xiaomi-pad-7.webp --file=scripts/images/xiaomi-pad-7.webp --content-type=image/webp
npx wrangler r2 object put --remote netereka/products/tablettes/xiaomi-pad-7-pro.webp --file=scripts/images/xiaomi-pad-7-pro.webp --content-type=image/webp
npx wrangler r2 object put --remote netereka/products/tablettes/redmi-pad-se-8-7.webp --file=scripts/images/redmi-pad-se-8-7.webp --content-type=image/webp
npx wrangler r2 object put --remote netereka/products/tablettes/honor-pad-10.webp --file=scripts/images/honor-pad-10.webp --content-type=image/webp
npx wrangler r2 object put --remote netereka/products/tablettes/oneplus-pad-3.webp --file=scripts/images/oneplus-pad-3.webp --content-type=image/webp
npx wrangler r2 object put --remote netereka/products/tablettes/redmagic-nova-gaming.webp --file=scripts/images/redmagic-nova-gaming.webp --content-type=image/webp
npx wrangler r2 object put --remote netereka/products/tablettes/redmi-pad-pro-5g.webp --file=scripts/images/redmi-pad-pro-5g.webp --content-type=image/webp
npx wrangler r2 object put --remote netereka/products/tablettes/redmi-pad-pro-wifi.webp --file=scripts/images/redmi-pad-pro-wifi.webp --content-type=image/webp
npx wrangler r2 object put --remote netereka/products/tablettes/redmi-pad-se.webp --file=scripts/images/redmi-pad-se.webp --content-type=image/webp
npx wrangler r2 object put --remote netereka/products/montres-connectees/apple-watch-series-10.webp --file=scripts/images/apple-watch-series-10.webp --content-type=image/webp
npx wrangler r2 object put --remote netereka/products/montres-connectees/apple-watch-ultra-2.webp --file=scripts/images/apple-watch-ultra-2.webp --content-type=image/webp
npx wrangler r2 object put --remote netereka/products/montres-connectees/huawei-watch-ultimate.webp --file=scripts/images/huawei-watch-ultimate.webp --content-type=image/webp
npx wrangler r2 object put --remote netereka/products/montres-connectees/huawei-watch-5.webp --file=scripts/images/huawei-watch-5.webp --content-type=image/webp
npx wrangler r2 object put --remote netereka/products/montres-connectees/huawei-watch-4-pro-space-edition.webp --file=scripts/images/huawei-watch-4-pro-space-edition.webp --content-type=image/webp
npx wrangler r2 object put --remote netereka/products/montres-connectees/huawei-watch-gt-5-pro-46mm-multicolore.webp --file=scripts/images/huawei-watch-gt-5-pro-46mm-multicolore.webp --content-type=image/webp
npx wrangler r2 object put --remote netereka/products/montres-connectees/huawei-watch-fit-4-pro.webp --file=scripts/images/huawei-watch-fit-4-pro.webp --content-type=image/webp
npx wrangler r2 object put --remote netereka/products/montres-connectees/huawei-watch-d2.webp --file=scripts/images/huawei-watch-d2.webp --content-type=image/webp
npx wrangler r2 object put --remote netereka/products/montres-connectees/samsung-watch-8.webp --file=scripts/images/samsung-watch-8.webp --content-type=image/webp
npx wrangler r2 object put --remote netereka/products/montres-connectees/apple-watch-se.webp --file=scripts/images/apple-watch-se.webp --content-type=image/webp
npx wrangler r2 object put --remote netereka/products/montres-connectees/apple-watch-series-9.webp --file=scripts/images/apple-watch-series-9.webp --content-type=image/webp
npx wrangler r2 object put --remote netereka/products/montres-connectees/redmi-watch-3-active.webp --file=scripts/images/redmi-watch-3-active.webp --content-type=image/webp
npx wrangler r2 object put --remote netereka/products/montres-connectees/redmi-watch-5.webp --file=scripts/images/redmi-watch-5.webp --content-type=image/webp
npx wrangler r2 object put --remote netereka/products/montres-connectees/redmi-watch-5-active.webp --file=scripts/images/redmi-watch-5-active.webp --content-type=image/webp
npx wrangler r2 object put --remote netereka/products/montres-connectees/redmi-watch-5-lite.webp --file=scripts/images/redmi-watch-5-lite.webp --content-type=image/webp
npx wrangler r2 object put --remote netereka/products/montres-connectees/xiaomi-smart-band-8-pro.webp --file=scripts/images/xiaomi-smart-band-8-pro.webp --content-type=image/webp
npx wrangler r2 object put --remote netereka/products/montres-connectees/xiaomi-smart-band-9.webp --file=scripts/images/xiaomi-smart-band-9.webp --content-type=image/webp
npx wrangler r2 object put --remote netereka/products/montres-connectees/xiaomi-smart-band-9-active.webp --file=scripts/images/xiaomi-smart-band-9-active.webp --content-type=image/webp
npx wrangler r2 object put --remote netereka/products/montres-connectees/xiaomi-smart-band-9-pro.webp --file=scripts/images/xiaomi-smart-band-9-pro.webp --content-type=image/webp
npx wrangler r2 object put --remote netereka/products/ordinateurs/macbook-pro-m3-max-2023.webp --file=scripts/images/macbook-pro-m3-max-2023.webp --content-type=image/webp
npx wrangler r2 object put --remote netereka/products/ordinateurs/macbook-pro-m3-2023.webp --file=scripts/images/macbook-pro-m3-2023.webp --content-type=image/webp
npx wrangler r2 object put --remote netereka/products/ordinateurs/macbook-pro-2023.webp --file=scripts/images/macbook-pro-2023.webp --content-type=image/webp
npx wrangler r2 object put --remote netereka/products/ordinateurs/macbook-pro-m2-2022.webp --file=scripts/images/macbook-pro-m2-2022.webp --content-type=image/webp
npx wrangler r2 object put --remote netereka/products/ordinateurs/macbook-air-m4-2025.webp --file=scripts/images/macbook-air-m4-2025.webp --content-type=image/webp
npx wrangler r2 object put --remote netereka/products/ordinateurs/macbook-air-m3-2023.webp --file=scripts/images/macbook-air-m3-2023.webp --content-type=image/webp
npx wrangler r2 object put --remote netereka/products/ordinateurs/macbook-air-m2-2024.webp --file=scripts/images/macbook-air-m2-2024.webp --content-type=image/webp
npx wrangler r2 object put --remote netereka/products/ordinateurs/macbook-air-m1-2021.webp --file=scripts/images/macbook-air-m1-2021.webp --content-type=image/webp
npx wrangler r2 object put --remote netereka/products/ordinateurs/macbook-pro-m4-2024.webp --file=scripts/images/macbook-pro-m4-2024.webp --content-type=image/webp
npx wrangler r2 object put --remote netereka/products/ordinateurs/macbook-pro-m4-max-2024.webp --file=scripts/images/macbook-pro-m4-max-2024.webp --content-type=image/webp
npx wrangler r2 object put --remote netereka/products/ordinateurs/macbook-pro-m4-pro-2024.webp --file=scripts/images/macbook-pro-m4-pro-2024.webp --content-type=image/webp
npx wrangler r2 object put --remote netereka/products/ordinateurs/imac-m3-2024.webp --file=scripts/images/imac-m3-2024.webp --content-type=image/webp
npx wrangler r2 object put --remote netereka/products/ordinateurs/imac-m4-2024.webp --file=scripts/images/imac-m4-2024.webp --content-type=image/webp
npx wrangler r2 object put --remote netereka/products/ordinateurs/dell-vostro-3520-i7.webp --file=scripts/images/dell-vostro-3520-i7.webp --content-type=image/webp
npx wrangler r2 object put --remote netereka/products/ordinateurs/bureau-hp-290-g9-i5.webp --file=scripts/images/bureau-hp-290-g9-i5.webp --content-type=image/webp
npx wrangler r2 object put --remote netereka/products/ordinateurs/bureau-hp-prodesk-400-g9-i5.webp --file=scripts/images/bureau-hp-prodesk-400-g9-i5.webp --content-type=image/webp
npx wrangler r2 object put --remote netereka/products/ordinateurs/lenovo-thinkbook-14-g6-i7.webp --file=scripts/images/lenovo-thinkbook-14-g6-i7.webp --content-type=image/webp
npx wrangler r2 object put --remote netereka/products/ordinateurs/lenovo-thinkbook-15-g4-i7.webp --file=scripts/images/lenovo-thinkbook-15-g4-i7.webp --content-type=image/webp
npx wrangler r2 object put --remote netereka/products/ordinateurs/lenovo-thinkpad-e14-g5-i7.webp --file=scripts/images/lenovo-thinkpad-e14-g5-i7.webp --content-type=image/webp
npx wrangler r2 object put --remote netereka/products/ordinateurs/lenovo-thinkpad-e15-i7.webp --file=scripts/images/lenovo-thinkpad-e15-i7.webp --content-type=image/webp
npx wrangler r2 object put --remote netereka/products/ordinateurs/lenovo-thinkpad-e16-i7.webp --file=scripts/images/lenovo-thinkpad-e16-i7.webp --content-type=image/webp
npx wrangler r2 object put --remote netereka/products/ordinateurs/lenovo-yoga-9-16-x360.webp --file=scripts/images/lenovo-yoga-9-16-x360.webp --content-type=image/webp
npx wrangler r2 object put --remote netereka/products/ordinateurs/dell-vostro-3030mt-i3.webp --file=scripts/images/dell-vostro-3030mt-i3.webp --content-type=image/webp
npx wrangler r2 object put --remote netereka/products/ordinateurs/dell-vostro-3030mt-i7.webp --file=scripts/images/dell-vostro-3030mt-i7.webp --content-type=image/webp
npx wrangler r2 object put --remote netereka/products/ordinateurs/lenovo-thinkcentre-neo-50t-i3.webp --file=scripts/images/lenovo-thinkcentre-neo-50t-i3.webp --content-type=image/webp
npx wrangler r2 object put --remote netereka/products/ordinateurs/hp-290-g9-i3.webp --file=scripts/images/hp-290-g9-i3.webp --content-type=image/webp
npx wrangler r2 object put --remote netereka/products/ecouteurs/freebuds-4-pro.webp --file=scripts/images/freebuds-4-pro.webp --content-type=image/webp
npx wrangler r2 object put --remote netereka/products/ecouteurs/freebuds-6.webp --file=scripts/images/freebuds-6.webp --content-type=image/webp
npx wrangler r2 object put --remote netereka/products/ecouteurs/freebuds-6i.webp --file=scripts/images/freebuds-6i.webp --content-type=image/webp
npx wrangler r2 object put --remote netereka/products/ecouteurs/galaxy-buds-3.webp --file=scripts/images/galaxy-buds-3.webp --content-type=image/webp
npx wrangler r2 object put --remote netereka/products/ecouteurs/galaxy-buds-3-pro.webp --file=scripts/images/galaxy-buds-3-pro.webp --content-type=image/webp
npx wrangler r2 object put --remote netereka/products/ecouteurs/huawei-freearc.webp --file=scripts/images/huawei-freearc.webp --content-type=image/webp
npx wrangler r2 object put --remote netereka/products/ecouteurs/huawei-freeclip.webp --file=scripts/images/huawei-freeclip.webp --content-type=image/webp
npx wrangler r2 object put --remote netereka/products/ecouteurs/oneplus-buds-pro-3.webp --file=scripts/images/oneplus-buds-pro-3.webp --content-type=image/webp
npx wrangler r2 object put --remote netereka/products/ecouteurs/mi-in-ear-headphones-basic.webp --file=scripts/images/mi-in-ear-headphones-basic.webp --content-type=image/webp
npx wrangler r2 object put --remote netereka/products/ecouteurs/redmi-buds-6.webp --file=scripts/images/redmi-buds-6.webp --content-type=image/webp
npx wrangler r2 object put --remote netereka/products/ecouteurs/redmi-buds-6-active.webp --file=scripts/images/redmi-buds-6-active.webp --content-type=image/webp
npx wrangler r2 object put --remote netereka/products/ecouteurs/redmi-buds-6-lite.webp --file=scripts/images/redmi-buds-6-lite.webp --content-type=image/webp
npx wrangler r2 object put --remote netereka/products/ecouteurs/redmi-buds-6-play.webp --file=scripts/images/redmi-buds-6-play.webp --content-type=image/webp
npx wrangler r2 object put --remote netereka/products/ecouteurs/redmi-buds-6-pro.webp --file=scripts/images/redmi-buds-6-pro.webp --content-type=image/webp
npx wrangler r2 object put --remote netereka/products/ecouteurs/xiaomi-buds-5.webp --file=scripts/images/xiaomi-buds-5.webp --content-type=image/webp
npx wrangler r2 object put --remote netereka/products/ecouteurs/xiaomi-buds-5-pro.webp --file=scripts/images/xiaomi-buds-5-pro.webp --content-type=image/webp
npx wrangler r2 object put --remote netereka/products/accessoires/airpods-4.webp --file=scripts/images/airpods-4.webp --content-type=image/webp
npx wrangler r2 object put --remote netereka/products/accessoires/airpods-4-anc.webp --file=scripts/images/airpods-4-anc.webp --content-type=image/webp
npx wrangler r2 object put --remote netereka/products/accessoires/airtag-pack-of-1.webp --file=scripts/images/airtag-pack-of-1.webp --content-type=image/webp
npx wrangler r2 object put --remote netereka/products/accessoires/airtag-pack-of-4.webp --file=scripts/images/airtag-pack-of-4.webp --content-type=image/webp
npx wrangler r2 object put --remote netereka/products/accessoires/apple-tv-4k-128gb-2025.webp --file=scripts/images/apple-tv-4k-128gb-2025.webp --content-type=image/webp
npx wrangler r2 object put --remote netereka/products/jeux/console-sony-ps5-slim-ea-fc-26.avif --file=scripts/images/console-sony-ps5-slim-ea-fc-26.avif --content-type=image/avif
npx wrangler r2 object put --remote netereka/products/jeux/ea-sports-fc-26.avif --file=scripts/images/ea-sports-fc-26.avif --content-type=image/avif
npx wrangler r2 object put --remote netereka/products/jeux/battlefield-6-pc.webp --file=scripts/images/battlefield-6-pc.webp --content-type=image/webp
npx wrangler r2 object put --remote netereka/products/televiseurs/ecran-lenovo-27-incurve-gaming.webp --file=scripts/images/ecran-lenovo-27-incurve-gaming.webp --content-type=image/webp
npx wrangler r2 object put --remote netereka/products/televiseurs/ecran-lenovo-34-incurve-gaming.webp --file=scripts/images/ecran-lenovo-34-incurve-gaming.webp --content-type=image/webp
npx wrangler r2 object put --remote netereka/products/televiseurs/ecran-philips-34-incurve-gaming.webp --file=scripts/images/ecran-philips-34-incurve-gaming.webp --content-type=image/webp